name: Intrinsics report
on: [push, pull_request, workflow_dispatch]
jobs:
  install:
    name: Install
    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - ocaml-compiler: 4.14.1
            os: ubuntu-latest
          - ocaml-compiler: 4.14.1
            os: macos-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          opam-pin: false
          opam-depext: false
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git

      - name: Deps
        run: |
          opam install ounit2
          opam pin add ocaml_intrinsics https://github.com/janestreet/ocaml_intrinsics.git

      - name: Build
        run: |
          opam exec -- dune build test.exe

      - name: Test
        run: |
          opam exec -- dune exec ./test.exe --  -ci true
